# a draft
# Файл должен начинаться с тега версии. Используем последнюю.
version: '3'
services:
  backend:
    build:
      context: .
    ports:
      # Перенаправляем запросы, поступающие к localhost:8080 на порт 8080.
      - 8080:8080
    volumes:
      # Задаём mount bind для каталога хост-машины. До запуска Docker Сompose нужно создать каталог host_volume
      - ./host_volume:/internal_volume

  postgres-fastapi:
    image: postgres:14.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: collection
    # a line below is not necessary. it can be deleted
    # entrypoint: [ "curl", "-s", "backend:8080" ]
    depends_on:
      - backend
