[tool.pytest.ini_options]
addopts = 'tests/test_routes.py::test_info tests/test_routes.py::test_deprecated -sv --capture=no'
pythonpath = 'src/'
# testpaths = ['tests/', ]  # not needed

[tool.ruff.lint]
extend-select=['I']

[tool.ruff.format]
quote-style='single'
