[tool.pytest.ini_options]
addopts = '-sv tests/test_routes.py::test_deprecated'
pythonpath = 'src/'
asyncio_mode = "auto"

[tool.ruff.lint]
extend-select=['I']

[tool.ruff.format]
quote-style='single'
